config:
  credentials: []
  project_repos:
    codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend:
      branch: main
      repo: https://codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-mustard-sheepdog.sh
        container: qc.acc_flaky-ivory-maltese
  QC.Doc:
    repos:
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-firebrick-greyhound.sh
        container: qc.doc_foggy-white-cattle
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-crimson-pig.sh
        container: qc.doc_squeaky-carmine-caiman
  QC.Lic:
    repos:
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-denim-booby.sh
        container: qc.lic_craggy-silver-starfish
  QC.Ver:
    repos:
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-celadon-armadillo.sh
        container: qc.ver_paltry-sapphire-flounder
timeout: 5400
