config:
  credentials: []
  project_repos:
    codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend:
      branch: main
      repo: https://codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-corn-caiman.sh
        container: qc.acc_zippy-periwinkle-hummingbird
  QC.Doc:
    repos:
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-chestnut-chow.sh
        container: qc.doc_lousy-russet-grouse
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-chestnut-mammoth.sh
        container: qc.doc_zippy-charcoal-baboon
  QC.Lic:
    repos:
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-persimmon-foxhound.sh
        container: qc.lic_hasty-xanthic-grouse
  QC.Ver:
    repos:
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-champagne-nightingale.sh
        container: qc.ver_smelly-vermilion-yak
timeout: 5400
