config:
  credentials: []
  project_repos:
    codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend:
      branch: main
      repo: https://codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-taupe-crab.sh
        container: qc.acc_lumpy-champagne-wallaby
  QC.Doc:
    repos:
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-smalt-zebra.sh
        container: qc.doc_ready-gold-barb
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-mustard-cougar.sh
        container: qc.doc_fuzzy-razzmatazz-mau
  QC.Lic:
    repos:
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-tangerine-panda.sh
        container: qc.lic_gummy-coral-axolotl
  QC.Ver:
    repos:
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-chocolate-seal.sh
        container: qc.ver_stinky-tan-weasel
timeout: 5400
