config:
  credentials: []
  project_repos:
    codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend:
      branch: main
      repo: https://codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-persimmon-goat.sh
        container: qc.acc_silly-pink-weasel
  QC.Doc:
    repos:
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-seashell-wombat.sh
        container: qc.doc_thirsty-alizarin-booby
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-cerise-wolf.sh
        container: qc.doc_freaky-mustard-greyhound
  QC.Lic:
    repos:
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-olive-saola.sh
        container: qc.lic_snippy-dandelion-buzzard
  QC.Ver:
    repos:
      codebase.helmholtz.cloud/m-team/ai/cookiecutter-web-backend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-viridian-chow.sh
        container: qc.ver_cozy-jade-avocet
timeout: 5400
