config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/fair-epos-prototype
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/m-team-kit/cookiecutter-web-backend:
      branch: main
      repo: https://github.com/m-team-kit/cookiecutter-web-backend
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/m-team-kit/cookiecutter-web-backend git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-cyan-coral.sh
        container: qc.acc_grumpy-turquoise-ray
  QC.Doc:
    repos:
      github.com/m-team-kit/cookiecutter-web-backend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-chestnut-sponge.sh
        container: qc.doc_lumpy-lilac-spaniel
      github.com/m-team-kit/cookiecutter-web-backend git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-aqua-cheetah.sh
        container: qc.doc_boozy-amber-macaw
  QC.Lic:
    repos:
      github.com/m-team-kit/cookiecutter-web-backend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-ivory-emu.sh
        container: qc.lic_hilly-beige-whippet
  QC.Ver:
    repos:
      github.com/m-team-kit/cookiecutter-web-backend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-jade-eleuth.sh
        container: qc.ver_lanky-periwinkle-kiwi
timeout: 5400
